import DataConnector from "@/dataConnectors/DataConnector";
//import { SessionUser } from "@/logic/SessionInfo.js";


/**
 * DataConnector for interacting with "Rooms".
 */
export default class GameplayDataConnector extends DataConnector {

  constructor() {
    super();
  }

  // Firebase functions for Game Play. -----------------------------


  //TODO - Test these, these were all just hacked together.........


  /**
   * Set the host.  
   * @param {number} newHostId - the unique user id of the new host - likely the current user 
   * @param {string} roomName 
   */
  updateHost = function (newHostId, roomName) {
    //let that = this;

    let roomDocRef = this.firestoreDb.doc(`rooms/${roomName}`);

    this.firestoreDb.runTransaction(function (transaction) {
      return transaction.get(roomDocRef).then(function () {
        transaction.update(roomDocRef, { hostId: newHostId });
      })
    })
  }

  updateSpectatorGameData = function (roomName, newSpecatorGameData) {
    //let that = this;

    let roomDocRef = this.firestoreDb.doc(`rooms/${roomName}`);

    this.firestoreDb.runTransaction(function (transaction) {
      return transaction.get(roomDocRef).then(function () {
        transaction.update(roomDocRef, { spectatorGameData: newSpecatorGameData });
      })
    })
  }

  //Set the whole playerGameData object - ignore prior state
  setPlayerGameData = function (roomName, newPlayerGameData) {
    //let that = this;

    let roomDocRef = this.firestoreDb.doc(`rooms/${roomName}`);

    this.firestoreDb.runTransaction(function (transaction) {
      return transaction.get(roomDocRef).then(function () {
        transaction.update(roomDocRef, { playerGameData: newPlayerGameData });
      })
    })
  }

  //Set a property in playerGameData, the rest of the object should remain as it was in firestore. 
  updatePlayerGameData = function (roomName, propName, propVal) {
    //let that = this;

    let roomDocRef = this.firestoreDb.doc(`rooms/${roomName}`);

    this.firestoreDb.runTransaction(function (transaction) {
      return transaction.get(roomDocRef).then(function (roomDoc) {


        let newPlayerGameData = roomDoc.data().playerGameData;
        newPlayerGameData[propName] = propVal;

        transaction.update(roomDocRef, { playerGameData: newPlayerGameData });
      })
    })
  }


  cleanPlayerGameData = function (roomName, propNamesArr) {
    //let that = this;

    let roomDocRef = this.firestoreDb.doc(`rooms/${roomName}`);

    this.firestoreDb.runTransaction(function (transaction) {
      return transaction.get(roomDocRef).then(function (roomDoc) {

        let newPlayerGameData = roomDoc.data().playerGameData;

        propNamesArr.forEach(name => {
          newPlayerGameData[name] = null;
        });

        transaction.update(roomDocRef, { playerGameData: newPlayerGameData });
      })
    })
  }

  updatePlayerGameDataViaFunction = function (roomName, updateFunc) {
    //let that = this;

    let roomDocRef = this.firestoreDb.doc(`rooms/${roomName}`);

    this.firestoreDb.runTransaction(function (transaction) {
      return transaction.get(roomDocRef).then(function (roomDoc) {

        let newPlayerGameData = roomDoc.data().playerGameData;        
        let updatedPlayerGameData = updateFunc(newPlayerGameData);       
        
        transaction.update(roomDocRef, { playerGameData: updatedPlayerGameData });
      })
    })
  }



  //TODO: The document is already being listened to because the data is part of the users room, unless this is extracted into a separate document we can probably get rid of this.

  //Stores the unsubscribe function generated by firestore when we setup a listener. 
  /*
  unsubscribeToPlayerGameDataFunc = null;

  listenToPlayerGameData = function (onSnapshotFunction, roomName) {

    //Don't subscribe to multiple rooms
    if (this.unsubscribeToPlayerGameDataFunc)
      this.unsubscribeToPlayerGameData();

    //While this should be a listener, I am concerned changes that aren't the userlist will be sent. 
    this.unsubscribeToPlayerGameDataFunc = this.firestoreDb
      .collection("rooms")
      .doc(roomName)
      .onSnapshot(function (doc) {
        let remotePlayerGameData = doc.data().playerGameData;
        onSnapshotFunction(remotePlayerGameData);
      });
  }

  unsubscribeToPlayerGameData = function () {
    if (this.unsubscribeToPlayerGameDataFunc) {
      this.unsubscribeToPlayerGameDataFunc();
      console.log("Unsubscribed to room!");
      this.unsubscribeToPlayerGameDataFunc = null;
    }
    else
      console.log("Nothing to unsubscribe from!");
  }
  */


}